services:
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./backend/.env
    environment:
      - DB_PATH=/app/data/data.sqlite
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:8080"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
