services:
  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    environment:
      - DB_PATH=/app/data/data.sqlite
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
      - backend_data_dev:/app/data
      - /app/node_modules
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      target: dev
    environment:
      - VITE_BACKEND_URL=http://backend:5000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_data_dev:
