sonar.organization=srik212
sonar.projectKey=Srik212_VibeSync---Blog-DevSecOps-Pipeline

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*
